# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  tatask:
    image: tatask
    build:
      context: .
      dockerfile: Task/Dockerfile
    ports:
      - 5050:5050
      - 5051:5051
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
